var R=require("../../../../../chunks/ssr/[turbopack]_runtime.js")("server/app/w/[slug]/projects/[pid]/page.js")
R.c("server/chunks/ssr/[root-of-the-server]__1avjyvu._.js")
R.c("server/chunks/ssr/node_modules_next_dist_0nkkbfv._.js")
R.c("server/chunks/ssr/[root-of-the-server]__0pocf1c._.js")
R.c("server/chunks/ssr/[root-of-the-server]__0gz0l81._.js")
R.c("server/chunks/ssr/[root-of-the-server]__1a9x63z._.js")
R.c("server/chunks/ssr/node_modules_next_dist_client_components_0wpq8j3._.js")
R.c("server/chunks/ssr/node_modules_next_dist_client_components_builtin_forbidden_0symwr9.js")
R.c("server/chunks/ssr/node_modules_next_dist_client_components_builtin_unauthorized_0l_sp0x.js")
R.c("server/chunks/ssr/node_modules_next_dist_client_components_builtin_global-error_0q-w892.js")
R.c("server/chunks/ssr/src_app_w_[slug]_layout_tsx_1ug_16g._.js")
R.c("server/chunks/ssr/_next-internal_server_app_w_[slug]_projects_[pid]_page_actions_096_rkx.js")
R.m(95073)
module.exports=R.m(95073).exports
