// This file is generated automatically by Next.js
// Do not edit this file manually

type AppRoutes = "/" | "/app" | "/onboarding" | "/sign-in" | "/sign-up" | "/w/[slug]" | "/w/[slug]/organization" | "/w/[slug]/projects" | "/w/[slug]/projects/[pid]" | "/w/[slug]/providers" | "/w/[slug]/settings"
type PageRoutes = never
type LayoutRoutes = "/" | "/w/[slug]"
type RedirectRoutes = never
type RewriteRoutes = "/api/[[...path]]"
type Routes = AppRoutes | PageRoutes | LayoutRoutes | RedirectRoutes | RewriteRoutes


interface ParamMap {
  "/": {}
  "/api/[[...path]]": { "path"?: string[]; }
  "/app": {}
  "/onboarding": {}
  "/sign-in": {}
  "/sign-up": {}
  "/w/[slug]": { "slug": string; }
  "/w/[slug]/organization": { "slug": string; }
  "/w/[slug]/projects": { "slug": string; }
  "/w/[slug]/projects/[pid]": { "slug": string; "pid": string; }
  "/w/[slug]/providers": { "slug": string; }
  "/w/[slug]/settings": { "slug": string; }
}


export type ParamsOf<Route extends Routes> = ParamMap[Route]

interface LayoutSlotMap {
  "/": never
  "/w/[slug]": never
}


export type { AppRoutes, PageRoutes, LayoutRoutes, RedirectRoutes, RewriteRoutes, ParamMap }

declare global {
  /**
   * Props for Next.js App Router page components
   * @example
   * ```tsx
   * export default function Page(props: PageProps<'/blog/[slug]'>) {
   *   const { slug } = await props.params
   *   return <div>Blog post: {slug}</div>
   * }
   * ```
   */
  interface PageProps<AppRoute extends AppRoutes> {
    params: Promise<ParamMap[AppRoute]>
    searchParams: Promise<Record<string, string | string[] | undefined>>
  }

  /**
   * Props for Next.js App Router layout components
   * @example
   * ```tsx
   * export default function Layout(props: LayoutProps<'/dashboard'>) {
   *   return <div>{props.children}</div>
   * }
   * ```
   */
  type LayoutProps<LayoutRoute extends LayoutRoutes> = {
    params: Promise<ParamMap[LayoutRoute]>
    children: React.ReactNode
  } & {
    [K in LayoutSlotMap[LayoutRoute]]: React.ReactNode
  }
}
