var R=require("../../chunks/ssr/[turbopack]_runtime.js")("server/app/onboarding/page.js")
R.c("server/chunks/ssr/[root-of-the-server]__0hsyp2u._.js")
R.c("server/chunks/ssr/node_modules_next_dist_0nkkbfv._.js")
R.c("server/chunks/ssr/[root-of-the-server]__0pocf1c._.js")
R.c("server/chunks/ssr/[root-of-the-server]__0gz0l81._.js")
R.c("server/chunks/ssr/[root-of-the-server]__1a9x63z._.js")
R.c("server/chunks/ssr/node_modules_next_dist_client_components_0wpq8j3._.js")
R.c("server/chunks/ssr/node_modules_next_dist_client_components_builtin_forbidden_0symwr9.js")
R.c("server/chunks/ssr/node_modules_next_dist_client_components_builtin_unauthorized_0l_sp0x.js")
R.c("server/chunks/ssr/node_modules_next_dist_client_components_builtin_global-error_0q-w892.js")
R.c("server/chunks/ssr/_next-internal_server_app_onboarding_page_actions_18b7irc.js")
R.m(37327)
module.exports=R.m(37327).exports
